/**
 * Embeds db/schema.sql into src/lib/schema-sql.ts.
 *
 * The serverless bundle does not reliably ship non-traced files, so the schema
 * travels as a TypeScript string constant instead of being read from disk.
 * Run automatically by `npm run prebuild`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";

const sql = readFileSync(new URL("../db/schema.sql", import.meta.url), "utf8");
const version = createHash("sha256").update(sql).digest("hex").slice(0, 16);
const escaped = sql.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

writeFileSync(
  new URL("../src/lib/schema-sql.ts", import.meta.url),
  `// AUTO-GENERATED by scripts/embed-schema.mjs — do not edit.\n` +
    `// Source of truth: db/schema.sql\n\n` +
    `export const SCHEMA_VERSION = ${JSON.stringify(version)};\n\n` +
    `export const SCHEMA_SQL = \`${escaped}\`;\n`
);

console.log(`schema-sql.ts written (version ${version}, ${sql.length} bytes)`);
